[package]
title = "ComfyUI Graph Editor"
description = "A built-in ComfyUI graph editor and Graph Model for the Omniverse platform"
version = "0.1.0"
authors = ["GliaCloud"]
repository = ""
keywords = ["graph", "ai", "editor"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
readme = "docs/README.md"
category = "Kit"
icon = "icons/icon.svg"

[dependencies]
"omni.ui" = {}
"omni.kit.graph.editor.core" = {}
"omni.kit.window.quicksearch" = {optional=true}
"omni.kit.window.filepicker" = {optional=true}
"omni.kit.window.popup_dialog" = {optional=true}
"omni.kit.graph.delegate.default" = {}
"omni.kit.graph.delegate.modern" = {}
"omni.kit.graph.delegate.neo" = {}
"omni.kit.menu.edit" = {}
"omni.kit.actions.core" = {}
"omni.services.core" = {}
"omni.services.transport.server.http" = {}
"omni.usd" = {}

[[python.module]]
name = "omni.comfyui.graph.editor"

[settings.exts."omni.comfyui.graph.editor"]
# URL prefix where the service will be mounted, where our API will be available to handle incoming requests.
#
# Defining this as a setting makes it easy to change or rebrand the endpoint using only command-line or KIT-file
# configuration instructions, should extensions ever feature conflicting endpoint naming conventions.
url_prefix = "/viewport-capture"

# Path from where the captured images will be served from, when exposed to clients.
#
# This path will be mounted as a child of the `url_prefix` setting, and expressed as a formatted join of the
# `{url_prefix}{capture_path}` settings.
capture_path = "/static"

# Name of the directory on the server where captured images will be stored:
capture_directory = "captured_stage_images"

[[test]]
dependencies = [
    "omni.kit.mainwindow",
    "omni.kit.renderer.capture",
    "omni.kit.renderer.core",
    "omni.kit.graph.editor.example",
    "omni.kit.graph.editor.core",
]

args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]

stdoutFailPatterns.exclude = [
    "*Failed to load texture*",
]