[package]
title = "ReShade preset editor window"
version = "0.2.1"
repository = ""
keywords = ["kit", "reshade"]

[dependencies]
"omni.ui" = {}
"omni.kit.viewport.utility" = {}
"omni.hydra.rtx" = {}

[[python.module]]
name = "rtx.reshade"

[[python.module]]
name = "omni.kit.window.reshade_editor"

# having "native" defined makes package separate for each platform & build config (bindings are shared libraries)
[native]

[[test]]
args = [
    "--/app/content/emptyStageOnStart=true",
    "--/rtx/reshade/enable=true"
]
dependencies = [
    "omni.kit.mainwindow",
    "omni.hydra.rtx",
    "omni.kit.window.viewport"
]

pythonTests.unreliable = [
    "*test_variable_list", # OM-99148
    "*test_technique_list", # OM-99148
]
