
[package]
    archivePath = "https://d4i3qtqj3r0z5.cloudfront.net/omni.kit.window.reshade_editor-d1d1da196b09d570.zip"

    [package.publish]
        kitVersion = "105.1.2+release.138975.ece658d9.tc"
        date = 1708076635
        buildNumber = "105.1.2+release.138975.ece658d9.tc"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp310"

        [package.target.platform]
            0 = "windows-x86_64"

        [package.target.kitHash]
            0 = "ece658d9"
